### PR TITLE
fix: A bug fix Update models.py

### PR DESCRIPTION
**Pull request by haozheng95**
fix error

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context.
I ran into this problem when I wanted to run the project. This was an issue（https://github.com/pydantic/pydantic/issues/3320） with pydantic, I fixed it by changing the properties of the models and my project was successfully running locally

My Python 3.11.9 

## Checklist before requesting a review

Please delete options that are not relevant.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code

## Screenshots (if appropriate):

```
File "/Users/baizhe/PycharmProjects/myquivr/.venv1/lib/python3.11/site-packages/pydantic/v1/validators.py", line 765, in find_validators
    raise RuntimeError(f'no validator found for {type_}, see `arbitrary_types_allowed` in Config')
RuntimeError: no validator found for <class 'langchain_core.documents.base.Document'>, see `arbitrary_types_allowed` in Config
```

### CODE REVIEW

**Comment by StanGirard** [comment]
@jacopo-chevallard can you check this one please ?

**Comment by jacopo-chevallard** [comment]
Hi @haozheng95, thanks for the PR. Could you, please, provide additional information on the error that triggered your fix so that I can try to reproduce it locally?

**Comment by haozheng95** [comment]
> Hi @haozheng95, thanks for the PR. Could you, please, provide additional information on the error that triggered your fix so that I can try to reproduce it locally?

`Python 3.11.9 `
`pydantic                     2.9.2
pydantic_core                2.23.4
`


Apple M1 Max
MAcOs Version 14.5 Beta(23F5059e)

My python Code
`llm = ChatGoogleGenerativeAI(model='gemini-1.5-flash', temperature=0.9)
if __name__ == "__main__":
    with tempfile.NamedTemporaryFile(mode="w", suffix=".txt") as temp_file:
        temp_file.write("Gold is a liquid of blue-like colour.")
        temp_file.flush()

        brain = Brain.from_files(
            name="test_brain",
            file_paths=[temp_file.name],
            llm=llm,
        )

        answer = brain.ask(
            "what is gold? asnwer in french"
        )
        print("answer:", answer)`

**Comment by jacopo-chevallard** [comment]
@haozheng95 I cannot reproduce the error, the issue is likely related to your package versions, in particular of LangChain.

You should be able to fix this be runnig `rye sync -f` from `examples/simple_question`, if not feel free to open an issue

**Pull request closed without merging**
