### PR TITLE
fix: sync folders  + notion sync

### PR DESCRIPTION
**Pull request by AmineDiro**
# Description

- Deserialization of notion results + fetching logic
- Fixed migration `notion_sync`
- Test deserialization of notion

### CODE REVIEW

**Review by chloedia — APPROVED** [review]
All Good to me !

**Comment by StanGirard** [comment]
Issues:
Chunks are empty

When updating a connection, it never creates a notification but doesn't delete it 
image
To reproduce -> update an existing connection

Adding a dropbox connexion fails, but then I can use it. To reproduce -> Add a new dropbox connection

In notion, the user_id is not a foreign key to the user 

In notion, when selecting a file and adding it it generates an error with punkt tab in the worker

**Comment by AmineDiro** [comment]
> Issues: Chunks are empty
Nltk dependency unstructured :( 

> When updating a connection, it creates a notification but doesn't delete it 
Nice catch ! 
> Adding a dropbox connexion fails, but then I can use it. To reproduce -> Add a new dropbox connection

> In notion, the user_id is not a foreign key to the user
I think this is the `user_id` in Notion not related to quivr. I think this is why we store it as string @chloedia  ? 🤔 

> In notion, when selecting a file and adding it it generates an error with punkt tab in the worker
working on this

**Comment by chloedia** [comment]
> > In notion, the user_id is not a foreign key to the user
> > I think this is the `user_id` in Notion not related to quivr. I think this is why we store it as string @chloedia  ? 🤔
-> No it is the user_id from Quivr, I just had  a lot of issues, but it can now be changed safely as a foreign key yo user !

**Pull request merged**
